
// DH11
#define DH11_READ_INTERVAL 10000


#define NUM_TEMP_SENSORS 8

/// pwm Info
#define PWM_FREQUENCY 40
#define PWM_RESOLUTION 8

#define X_AXIS 0
#define Y_AXIS 1
#define Z_AXIS 2
#define E_AXIS 3

#define X_AXIS_CHANNEL X_AXIS
#define Y_AXIS_CHANNEL Y_AXIS
#define Z_AXIS_CHANNEL Z_AXIS
#define E_AXIS_CHANNEL E_AXIS

#define DS18B20
#define TEMP_READING_INTERVAL 10000